package fortnox

// CountryMap is a mapping of fortnox's internal country strings. Can be handy if you need the country code.
// TODO - remove when fortnox send CountryCode in orders/invoices
var CountryMap = map[string]string{
	"Afghanistan":                     "AF",
	"Åland":                           "AX",
	"Åland Islands":                   "AX",
	"Albania":                         "AL",
	"Albanien":                        "AL",
	"Algeria":                         "DZ",
	"Algeriet":                        "DZ",
	"American Samoa":                  "AS",
	"Amerikanska Jungfruöarna":        "VI",
	"Amerikanska Samoa":               "AS",
	"Andorra":                         "AD",
	"Angola":                          "AO",
	"Anguilla":                        "AI",
	"Antarctica":                      "AQ",
	"Antarktis":                       "AQ",
	"Antigua and Barbuda":             "AG",
	"Antigua och Barbuda":             "AG",
	"Argentina":                       "AR",
	"Armenia":                         "AM",
	"Armenien":                        "AM",
	"Aruba":                           "AW",
	"Australia":                       "AU",
	"Australien":                      "AU",
	"Austria":                         "AT",
	"Azerbaijan":                      "AZ",
	"Azerbajdzjan":                    "AZ",
	"Bahamas":                         "BS",
	"Bahrain":                         "BH",
	"Bangladesh":                      "BD",
	"Barbados":                        "BB",
	"Belarus":                         "BY",
	"Belgien":                         "BE",
	"Belgium":                         "BE",
	"Belize":                          "BZ",
	"Benin":                           "BJ",
	"Bermuda":                         "BM",
	"Bhutan":                          "BT",
	"Bolivia":                         "BO",
	"Bolivia, Plurinational State of": "BO",
	"Bosnia and Herzegovina":          "BA",
	"Bosnien och Hercegovina":         "BA",
	"Botswana":                        "BW",
	"Bouvet Island":                   "BV",
	"Bouvetön":                        "BV",
	"Brasilien":                       "BR",
	"Brazil":                          "BR",
	"British Indian Ocean Territory":          "IO",
	"Brittiska Jungfruöarna":                  "VG",
	"Brittiska territoriet i Indiska Oceanen": "IO",
	"Brunei":                       "BN",
	"Brunei Darussalam":            "BN",
	"Bulgaria":                     "BG",
	"Bulgarien":                    "BG",
	"Burkina Faso":                 "BF",
	"Burma":                        "MM",
	"Burundi":                      "BI",
	"Cambodia":                     "KH",
	"Cameroon":                     "CM",
	"Canada":                       "CA",
	"Cape Verde":                   "CV",
	"Cayman Islands":               "KY",
	"Caymanöarna":                  "KY",
	"Central African Republic":     "CF",
	"Centralafrikanska republiken": "CF",
	"Chad":                    "TD",
	"Chile":                   "CL",
	"China":                   "CN",
	"Christmas Island":        "CX",
	"Cocos (Keeling) Islands": "CC",
	"Colombia":                "CO",
	"Comoros":                 "KM",
	"Congo":                   "CG",
	"Congo, the Democratic Republic of the": "CD",
	"Cook Islands":                          "CK",
	"Cooköarna":                             "CK",
	"Costa Rica":                            "CR",
	"Côte d'Ivoire":                         "CI",
	"Croatia":                               "HR",
	"Cuba":                                  "CU",
	"Cypern":                                "CY",
	"Cyprus":                                "CY",
	"Czech Republic":                        "CZ",
	"Danmark":                               "DK",
	"Demokratiska republiken Kongo":         "CD",
	"Denmark":                               "DK",
	"Djibouti":                              "DJ",
	"Dominica":                              "DM",
	"Dominican Republic":                    "DO",
	"Dominikanska republiken":               "DO",
	"Ecuador":                               "EC",
	"Egypt":                                 "EG",
	"Egypten":                               "EG",
	"Ekvatorialguinea":                      "GQ",
	"Elfenbenskusten":                       "CI",
	"El Salvador":                           "SV",
	"Equatorial Guinea":                     "GQ",
	"Eritrea":                               "ER",
	"Estland":                               "EE",
	"Estonia":                               "EE",
	"Ethiopia":                              "ET",
	"Etiopien":                              "ET",
	"Falkland Islands (Malvinas)":           "FK",
	"Falklandsöarna":                        "FK",
	"Färöarna":                              "FO",
	"Faroe Islands":                         "FO",
	"Fiji":                                  "FJ",
	"Filippinerna":                          "PH",
	"Finland":                               "FI",
	"Förenade Arabemiraten":                 "AE",
	"France":                                "FR",
	"France métropolitaine (Frankrike, europeiska delen)": "FX",
	"France, Metropolitan":                                "FX",
	"Frankrike":                                           "FR",
	"Franska Guyana":                                      "GF",
	"Franska Polynesien":                                  "PF",
	"Franska södra territorierna":                         "TF",
	"French Guiana":                                       "GF",
	"French Polynesia":                                    "PF",
	"French Southern Territories":                         "TF",
	"Gabon":         "GA",
	"Gambia":        "GM",
	"Georgia":       "GE",
	"Georgien":      "GE",
	"Germany":       "DE",
	"Ghana":         "GH",
	"Gibraltar":     "GI",
	"Greece":        "GR",
	"Greenland":     "GL",
	"Grekland":      "GR",
	"Grenada":       "GD",
	"Grönland":      "GL",
	"Guadeloupe":    "GP",
	"Guam":          "GU",
	"Guatemala":     "GT",
	"Guernsey":      "GG",
	"Guinea Bissau": "GW",
	"Guinea-Bissau": "GW",
	"Guinea":        "GN",
	"Guyana":        "GY",
	"Haiti":         "HT",
	"Heard Island and McDonald Islands": "HM",
	"Heard- och McDonaldsöarna":         "HM",
	"Holy See (Vatican City State)":     "VA",
	"Honduras":                          "HN",
	"Hongkong":                          "HK",
	"Hong Kong":                         "HK",
	"Hungary":                           "HU",
	"Iceland":                           "IS",
	"India":                             "IN",
	"Indien":                            "IN",
	"Indonesia":                         "ID",
	"Indonesien":                        "ID",
	"Irak":                              "IQ",
	"Iran":                              "IR",
	"Iran, Islamic Republic of": "IR",
	"Iraq":                                   "IQ",
	"Ireland":                                "IE",
	"Irland":                                 "IE",
	"Island":                                 "IS",
	"Isle of Man":                            "IM",
	"Israel":                                 "IL",
	"Italien":                                "IT",
	"Italy":                                  "IT",
	"Jamaica":                                "JM",
	"Japan":                                  "JP",
	"Jemen":                                  "YE",
	"Jersey":                                 "JE",
	"Jordanien":                              "JO",
	"Jordan":                                 "JO",
	"Julön":                                  "CX",
	"Kambodja":                               "KH",
	"Kamerun":                                "CM",
	"Kanada":                                 "CA",
	"Kap Verde":                              "CV",
	"Kazakhstan":                             "KZ",
	"Kazakstan":                              "KZ",
	"Kenya":                                  "KE",
	"Kina":                                   "CN",
	"Kirgizistan":                            "KG",
	"Kiribati":                               "KI",
	"Kokosöarna":                             "CC",
	"Komorerna":                              "KM",
	"Kongo-Brazzaville":                      "CG",
	"Korea, Democratic People's Republic of": "KP",
	"Korea, Republic of":                     "KR",
	"Kroatien":                               "HR",
	"Kuba":                                   "CU",
	"Kuwait":                                 "KW",
	"Kyrgyzstan":                             "KG",
	"Lao People's Democratic Republic":       "LA",
	"Laos":          "LA",
	"Latvia":        "LV",
	"Lebanon":       "LB",
	"Lesotho":       "LS",
	"Lettland":      "LV",
	"Libanon":       "LB",
	"Liberia":       "LR",
	"Libya":         "LY",
	"Libyen":        "LY",
	"Liechtenstein": "LI",
	"Litauen":       "LT",
	"Lithuania":     "LT",
	"Luxembourg":    "LU",
	"Luxemburg":     "LU",
	"Macao":         "MO",
	"Macau":         "MO",
	"Macedonia, the former Yugoslav Republic of": "MK",
	"Madagascar":                                 "MG",
	"Madagaskar":                                 "MG",
	"Makedonien":                                 "MK",
	"Malawi":                                     "MW",
	"Malaysia":                                   "MY",
	"Maldiverna":                                 "MV",
	"Maldives":                                   "MV",
	"Mali":                                       "ML",
	"Malta":                                      "MT",
	"Marocko":                                    "MA",
	"Marshall Islands":                           "MH",
	"Marshallöarna":                              "MH",
	"Martinique":                                 "MQ",
	"Mauretanien":                                "MR",
	"Mauritania":                                 "MR",
	"Mauritius":                                  "MU",
	"Mayotte":                                    "YT",
	"Mexico":                                     "MX",
	"Mexiko":                                     "MX",
	"Micronesia, Federated States of":              "FM",
	"Mikronesiska federationen":                    "FM",
	"Moçambique":                                   "MZ",
	"Moldavien":                                    "MD",
	"Moldova, Republic of":                         "MD",
	"Monaco":                                       "MC",
	"Mongolia":                                     "MN",
	"Mongoliet":                                    "MN",
	"Montenegro":                                   "ME",
	"Montserrat":                                   "MS",
	"Morocco":                                      "MA",
	"Mozambique":                                   "MZ",
	"Myanmar":                                      "MM",
	"Namibia":                                      "NA",
	"Nauru":                                        "NR",
	"Nederländerna":                                "NL",
	"Nederländska Antillerna":                      "AN",
	"Nepal":                                        "NP",
	"Netherlands Antilles":                         "AN",
	"Netherlands":                                  "NL",
	"New Caledonia":                                "NC",
	"New Zealand":                                  "NZ",
	"Nicaragua":                                    "NI",
	"Nigeria":                                      "NG",
	"Niger":                                        "NE",
	"Niue":                                         "NU",
	"Nordkorea":                                    "KP",
	"Nordmarianerna":                               "MP",
	"Norfolk Island":                               "NF",
	"Norfolkön":                                    "NF",
	"Norge":                                        "NO",
	"Northern Mariana Islands":                     "MP",
	"Norway":                                       "NO",
	"Nya Kaledonien":                               "NC",
	"Nya Zeeland":                                  "NZ",
	"Oman":                                         "OM",
	"Österrike":                                    "AT",
	"Östtimor":                                     "TL",
	"Pakistan":                                     "PK",
	"Palau":                                        "PW",
	"Panama":                                       "PA",
	"Papua New Guinea":                             "PG",
	"Papua Nya Guinea":                             "PG",
	"Paraguay":                                     "PY",
	"Peru":                                         "PE",
	"Philippines":                                  "PH",
	"Pitcairnöarna":                                "PN",
	"Pitcairn":                                     "PN",
	"Poland":                                       "PL",
	"Polen":                                        "PL",
	"Portugal":                                     "PT",
	"Puerto Rico":                                  "PR",
	"Qatar":                                        "QA",
	"Réunion":                                      "RE",
	"Romania":                                      "RO",
	"Rumänien":                                     "RO",
	"Russian Federation":                           "RU",
	"Rwanda":                                       "RW",
	"Ryssland":                                     "RU",
	"Saint Barthélemy":                             "BL",
	"Saint-Barthélemy":                             "BL",
	"Saint Helena, Ascension and Tristan da Cunha": "SH",
	"Saint Kitts and Nevis":                        "KN",
	"Saint Kitts och Nevis":                        "KN",
	"Saint Lucia":                                  "LC",
	"Saint Pierre and Miquelon":                    "PM",
	"Saint-Pierre och Miquelon":                    "PM",
	"Saint Vincent and the Grenadines":             "VC",
	"Saint Vincent och Grenadinerna":               "VC",
	"Salomonöarna":                                 "SB",
	"Samoa":                                        "WS",
	"Sankta Helena":                                "SH",
	"San Marino":                                   "SM",
	"Sao Tome and Principe":                        "ST",
	"São Tomé och Príncipe":                        "ST",
	"Saudi Arabia":                                 "SA",
	"Saudiarabien":                                 "SA",
	"Schweiz":                                      "CH",
	"Senegal":                                      "SN",
	"Serbia":                                       "RS",
	"Serbien":                                      "RS",
	"Seychellerna":                                 "SC",
	"Seychelles":                                   "SC",
	"Sierra Leone":                                 "SL",
	"Singapore":                                    "SG",
	"Slovakia":                                     "SK",
	"Slovakien":                                    "SK",
	"Slovenia":                                     "SI",
	"Slovenien":                                    "SI",
	"Solomon Islands":                              "SB",
	"Somalia":                                      "SO",
	"South Africa":                                 "ZA",
	"Spain":                                        "ES",
	"Spanien":                                      "ES",
	"Sri Lanka":                                    "LK",
	"Storbritannien":                               "GB",
	"Sudan":                                        "SD",
	"Suriname":                                     "SR",
	"Surinam":                                      "SR",
	"Svalbard and Jan Mayen":                       "SJ",
	"Svalbard och Jan Mayen":                       "SJ",
	"Sverige":                                      "SE",
	"Swaziland":                                    "SZ",
	"Sweden":                                       "SE",
	"Switzerland":                                  "CH",
	"Sydafrika":                                    "ZA",
	"Sydkorea":                                     "KR",
	"Syrian Arab Republic":                         "SY",
	"Syrien":                                       "SY",
	"Tadzjikistan":                                 "TJ",
	"Taiwan, Province of China":                    "TW",
	"Taiwan":                                       "TW",
	"Tajikistan":                                   "TJ",
	"Tanzania":                                     "TZ",
	"Tanzania, United Republic of":                 "TZ",
	"Tchad":                                "TD",
	"Thailand":                             "TH",
	"Timor-Leste":                          "TL",
	"Tjeckien":                             "CZ",
	"Togo":                                 "TG",
	"Tokelauöarna":                         "TK",
	"Tokelau":                              "TK",
	"Tonga":                                "TO",
	"Trinidad and Tobago":                  "TT",
	"Trinidad och Tobago":                  "TT",
	"Tunisia":                              "TN",
	"Tunisien":                             "TN",
	"Turkey":                               "TR",
	"Turkiet":                              "TR",
	"Turkmenistan":                         "TM",
	"Turks and Caicos Islands":             "TC",
	"Turks- och Caicosöarna":               "TC",
	"Tuvalu":                               "TV",
	"Tyskland":                             "DE",
	"Uganda":                               "UG",
	"Ukraina":                              "UA",
	"Ukraine":                              "UA",
	"Ungern":                               "HU",
	"United Arab Emirates":                 "AE",
	"United Kingdom":                       "GB",
	"United States Minor Outlying Islands": "UM",
	"United States":                        "US",
	"Uruguay":                              "UY",
	"USA:s yttre öar":                      "UM",
	"USA":                                  "US",
	"Uzbekistan":                           "UZ",
	"Vanuatu":                              "VU",
	"Västsahara":                           "EH",
	"Vatikanstaten":                        "VA",
	"Venezuela, Bolivarian Republic of":    "VE",
	"Venezuela":                            "VE",
	"Vietnam":                              "VN",
	"Viet Nam":                             "VN",
	"Virgin Islands, British":              "VG",
	"Virgin Islands, U.S.":                 "VI",
	"Vitryssland":                          "BY",
	"Wallis and Futuna":                    "WF",
	"Wallis- och Futunaöarna":              "WF",
	"Western Sahara":                       "EH",
	"Yemen":                                "YE",
	"Zambia":                               "ZM",
	"Zimbabwe":                             "ZW",
}
